# Generated by Django 5.1.15 on 2026-09-25 11:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.CharField(max_length=50, unique=True, verbose_name='Interne Fahrzeugnummer')),
                ('brand', models.CharField(max_length=100, verbose_name='Marke')),
                ('model', models.CharField(max_length=120, verbose_name='Modell')),
                ('variant', models.CharField(blank=True, max_length=150, verbose_name='Variante / Modellbezeichnung')),
                ('vehicle_type', models.CharField(max_length=80, verbose_name='Fahrzeugtyp')),
                ('first_registration', models.DateField(verbose_name='Erstzulassung')),
                ('year', models.PositiveIntegerField(verbose_name='Baujahr')),
                ('mileage', models.PositiveIntegerField(verbose_name='Kilometerstand')),
                ('fuel_type', models.CharField(max_length=60, verbose_name='Kraftstoffart')),
                ('transmission', models.CharField(max_length=50, verbose_name='Getriebe')),
                ('power_kw', models.PositiveIntegerField(verbose_name='Leistung kW')),
                ('power_ps', models.PositiveIntegerField(verbose_name='Leistung PS')),
                ('engine_capacity', models.PositiveIntegerField(verbose_name='Hubraum')),
                ('doors', models.PositiveIntegerField(verbose_name='Anzahl Türen')),
                ('seats', models.PositiveIntegerField(verbose_name='Anzahl Sitzplätze')),
                ('exterior_color', models.CharField(max_length=80, verbose_name='Außenfarbe')),
                ('interior_equipment', models.CharField(blank=True, max_length=200, verbose_name='Innenausstattung')),
                ('vin', models.CharField(blank=True, max_length=50, verbose_name='FIN / Fahrgestellnummer')),
                ('previous_owners', models.PositiveIntegerField(default=0, verbose_name='Anzahl Vorbesitzer')),
                ('hu_valid_until', models.DateField(blank=True, null=True, verbose_name='HU gültig bis')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Einkaufspreis')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Verkaufspreis')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('equipment', models.TextField(blank=True, verbose_name='Ausstattung')),
                ('status', models.CharField(choices=[('in_preparation', 'In Vorbereitung'), ('available', 'Verfügbar'), ('reserved', 'Reserviert'), ('sold', 'Verkauft')], default='in_preparation', max_length=30, verbose_name='Status')),
                ('is_published', models.BooleanField(default=False, verbose_name='Veröffentlicht')),
                ('public_visible', models.BooleanField(default=False, verbose_name='Öffentlich sichtbar')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum der Aufnahme')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum der letzten Änderung')),
            ],
            options={
                'verbose_name': 'Fahrzeug',
                'verbose_name_plural': 'Fahrzeuge',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inquiry_type', models.CharField(choices=[('vehicle_request', 'Fahrzeug anfragen'), ('test_drive', 'Probefahrt anfragen')], default='vehicle_request', max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Kundenanfrage',
                'verbose_name_plural': 'Kundenanfragen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAIText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_type', models.CharField(choices=[('short_description', 'Kurze Fahrzeugbeschreibung'), ('long_description', 'Ausführliche Fahrzeugbeschreibung'), ('seo_text', 'SEO-Text'), ('social_text', 'Social-Media-Text'), ('translation_de', 'Übersetzung Deutsch'), ('translation_en', 'Übersetzung Englisch'), ('translation_es', 'Übersetzung Spanisch')], max_length=40)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_texts', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'KI-Text',
                'verbose_name_plural': 'KI-Texte',
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/%Y/%m/%d/', verbose_name='Bild')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt-Text')),
                ('is_main', models.BooleanField(default=False, verbose_name='Hauptbild')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Fahrzeugbild',
                'verbose_name_plural': 'Fahrzeugbilder',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
