# Generated by Django 5.1.15 on 2026-09-25 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/%Y/%m/')),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Überschrift')),
                ('excerpt', models.CharField(max_length=350, verbose_name='Kurztext')),
                ('body', models.TextField(verbose_name='Beitrag')),
                ('image', models.ImageField(blank=True, upload_to='news/%Y/%m/', verbose_name='Titelbild')),
                ('image_alt', models.CharField(blank=True, max_length=200, verbose_name='Bildbeschreibung')),
                ('is_published', models.BooleanField(default=False, verbose_name='Veröffentlichen')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Neuigkeit',
                'verbose_name_plural': 'Neuigkeiten',
                'ordering': ['-published_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Bezeichnung')),
                ('category', models.CharField(choices=[('tires', 'Reifen'), ('wheels', 'Felgen & Kompletträder'), ('parts', 'Autoteile'), ('other', 'Zubehör')], max_length=20, verbose_name='Kategorie')),
                ('condition', models.CharField(choices=[('new', 'Neu'), ('used', 'Gebraucht')], default='used', max_length=10, verbose_name='Zustand')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('compatibility', models.CharField(blank=True, max_length=250, verbose_name='Passend für / Maße')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis in Euro')),
                ('status', models.CharField(choices=[('available', 'Verfügbar'), ('reserved', 'Reserviert'), ('sold', 'Verkauft')], default='available', max_length=20, verbose_name='Verkaufsstatus')),
                ('is_published', models.BooleanField(default=False, verbose_name='Auf der Website veröffentlichen')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zubehörangebot',
                'verbose_name_plural': 'Zubehörangebote',
                'ordering': ['-updated_at', '-pk'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='accessory_price_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='AccessoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='accessories/%Y/%m/', verbose_name='Bild')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Bildbeschreibung')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge (kleinste Zahl = Hauptbild)')),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.accessory')),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('draft', models.JSONField(default=dict)),
                ('published', models.JSONField(default=dict)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Startseite',
                'verbose_name_plural': 'Startseite',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='homepage_singleton')],
            },
        ),
    ]
