# Generated by Django 5.1.15 on 2026-09-25 22:19

import vehicles.slider_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_homepageimage_newsarticle_accessory_accessoryimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=180, verbose_name='Titel')),
                ('subtitle', models.TextField(blank=True, max_length=500, verbose_name='Untertitel')),
                ('image', models.ImageField(help_text='JPEG, PNG oder WebP, höchstens 10 MB. Querformat empfohlen.', upload_to='homepage/slides/%Y/%m/', verbose_name='Bild')),
                ('image_alt', models.CharField(blank=True, help_text='Beschreiben Sie das Motiv. Bei rein dekorativen Bildern leer lassen.', max_length=200, verbose_name='Bildbeschreibung')),
                ('button_text', models.CharField(blank=True, max_length=60, verbose_name='Button-Text')),
                ('button_url', models.CharField(blank=True, help_text='Interner Pfad wie /fahrzeuge/ oder vollständiger https://-Link.', max_length=500, validators=[vehicles.slider_validation.validate_slide_link], verbose_name='Button-Link')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Kleinere Zahlen erscheinen zuerst.', verbose_name='Reihenfolge')),
                ('is_active', models.BooleanField(default=False, help_text='Aktive Slides sind nach dem Speichern sofort öffentlich sichtbar.', verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Geändert')),
            ],
            options={
                'verbose_name': 'Startseiten-Slide',
                'verbose_name_plural': 'Startseiten-Slides',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
