# Generated by Django 5.1.15 on 2026-09-26 10:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_import_homepage_slides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=10000, verbose_name='Antworttext')),
                ('recipient', models.EmailField(editable=False, max_length=254, verbose_name='Empfänger')),
                ('subject', models.CharField(editable=False, max_length=320, verbose_name='Betreff')),
                ('status', models.CharField(choices=[('sending', 'Versand läuft / Ergebnis offen'), ('sent', 'An Mailserver übergeben'), ('failed', 'Versand fehlgeschlagen'), ('test', 'Nur im Testbetrieb protokolliert')], default='sending', max_length=16, verbose_name='Versandstatus')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Versanddatum')),
            ],
            options={
                'verbose_name': 'Antwort auf Kundenanfrage',
                'verbose_name_plural': 'Antwortverlauf',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'permissions': [('change_slider_settings', 'Kann Slider-Einstellungen ändern')], 'verbose_name': 'Startseite', 'verbose_name_plural': 'Startseite'},
        ),
        migrations.AddField(
            model_name='customerinquiry',
            name='status',
            field=models.CharField(choices=[('new', 'Neu'), ('read', 'Gelesen'), ('in_progress', 'In Bearbeitung'), ('answered', 'Beantwortet'), ('done', 'Erledigt')], db_index=True, default='new', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='customerinquiry',
            name='subject',
            field=models.CharField(blank=True, editable=False, max_length=300, verbose_name='Betreff'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slider_interval',
            field=models.PositiveSmallIntegerField(default=4, help_text='Zwischen 2 und 30 Sekunden. Änderungen gelten sofort für den Slider.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)], verbose_name='Wechselgeschwindigkeit in Sekunden'),
        ),
        migrations.AddConstraint(
            model_name='homepage',
            constraint=models.CheckConstraint(condition=models.Q(('slider_interval__gte', 2), ('slider_interval__lte', 30)), name='homepage_slider_interval_range'),
        ),
        migrations.AddField(
            model_name='inquiryreply',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiryreply',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='vehicles.customerinquiry'),
        ),
    ]
