# Generated by Django 5.1.15 on 2026-09-26 11:03

import django.core.validators
from django.db import migrations, models


def clamp_interval(apps, schema_editor):
    Homepage = apps.get_model('vehicles', 'Homepage')
    Homepage.objects.using(schema_editor.connection.alias).filter(slider_interval__gt=15).update(slider_interval=15)


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_inquiry_subject_snapshot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='homepage',
            name='homepage_slider_interval_range',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='slider_interval',
            field=models.PositiveSmallIntegerField(default=4, help_text='Zwischen 2 und 15 Sekunden. Änderungen gelten sofort für den Slider.', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(15)], verbose_name='Wechselgeschwindigkeit in Sekunden'),
        ),
        migrations.RunPython(clamp_interval, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='homepage',
            constraint=models.CheckConstraint(condition=models.Q(('slider_interval__gte', 2), ('slider_interval__lte', 15)), name='homepage_slider_interval_range'),
        ),
    ]
