# Generated by Django 5.1.15 on 2026-09-26 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_remove_homepage_homepage_slider_interval_range_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinquiry',
            name='financing_annual_rate',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='customerinquiry',
            name='financing_downpayment',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customerinquiry',
            name='financing_final_payment',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customerinquiry',
            name='financing_monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='customerinquiry',
            name='financing_term_months',
            field=models.PositiveSmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='customerinquiry',
            name='financing_vehicle_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='financing_annual_rate',
            field=models.DecimalField(decimal_places=2, default='6.99', help_text='Zentrale Einstellung für fahrzeugbezogene Finanzierungsrechner.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Effektiver Jahreszins in Prozent'),
        ),
        migrations.AlterField(
            model_name='customerinquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('vehicle_request', 'Fahrzeug anfragen'), ('test_drive', 'Probefahrt anfragen'), ('financing_request', 'Finanzierung anfragen')], default='vehicle_request', max_length=30),
        ),
    ]
