# Generated by Django 5.1.15 on 2026-09-26 17:41

import django.db.models.deletion
import django.utils.text
import django.utils.timezone
from django.db import migrations, models


def migrate_news_data(apps, schema_editor):
    NewsArticle = apps.get_model('vehicles', 'NewsArticle')
    for article in NewsArticle.objects.all().iterator():
        base_slug = django.utils.text.slugify(article.title) or f'neuigkeit-{article.pk}'
        slug = base_slug
        suffix = 2
        while NewsArticle.objects.filter(slug=slug).exclude(pk=article.pk).exists():
            slug = f'{base_slug}-{suffix}'
            suffix += 1
        article.slug = slug
        article.status = 'published' if article.is_published else 'draft'
        if article.is_published and article.published_at is None:
            article.published_at = django.utils.timezone.now()
        article.save(update_fields=['slug', 'status', 'published_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_customerinquiry_financing_annual_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-is_featured', '-published_at', '-pk'], 'verbose_name': 'Neuigkeit', 'verbose_name_plural': 'Neuigkeiten'},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gültig bis'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='event_date',
            field=models.DateField(blank=True, null=True, verbose_name='Veranstaltungsdatum'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='event_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Veranstaltungsort'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='event_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Uhrzeit'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Hervorgehoben'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, verbose_name='URL-Adresse'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('published', 'Veröffentlicht'), ('archived', 'Archiviert')], default='draft', max_length=12, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='type',
            field=models.CharField(choices=[('news', 'News'), ('vehicle', 'Neues Fahrzeug'), ('offer', 'Angebot / Aktion'), ('company', 'Unternehmen'), ('event', 'Event'), ('notice', 'Hinweis')], default='news', max_length=12, verbose_name='News-Typ'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='vehicles.vehicle', verbose_name='Verknüpftes Fahrzeug'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='body',
            field=models.TextField(blank=True, verbose_name='Inhalt'),
        ),
        migrations.RunPython(migrate_news_data, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='newsarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL-Adresse'),
        ),
        migrations.RemoveField(
            model_name='newsarticle',
            name='is_published',
        ),
    ]
