"""Editable homepage copy, with the existing site content as fallback."""
TEXT_FIELDS = [
    ('page_title', 'Seitentitel', 'Auto Wallstein | Mercedes-Benz Jahreswagen', 'Startbereich'),
    ('hero_title', 'Hauptüberschrift / Ersatz-Slide', 'Mercedes Benz Jahres-& Geschäftswagen', 'Startbereich'),
    ('hero_text', 'Text für Ersatz-Slide', 'Entdecke aktuelle Angebote aus unserem Bestand und finde das passende Fahrzeug für dich.', 'Startbereich'),
    ('hero_button', 'Button für Ersatz-Slide', 'Fahrzeuge ansehen', 'Startbereich'),
    ('welcome_title', 'Begrüßung – Überschrift', 'FINDEN SIE IHREN NÄCHSTEN MERCEDES.', 'Begrüßung'),
    ('welcome_text', 'Begrüßung – Text', 'Willkommen bei Auto Wallstein. Entdecken Sie erstklassige Jahres- und Geschäftswagen von Mercedes-Benz. Profitieren Sie von unserer Kompetenz und exklusivem Zugriff auf über 5.000 Fahrzeuge der Mercedes-Benz AG. Ihr Traumwagen wartet auf Sie – besuchen Sie uns in Heusenstamm.', 'Begrüßung'),
    ('tile_vehicles', 'Fahrzeugsuche – Beschriftung', 'Fahrzeugsuche', 'Bildkacheln'),
    ('tile_service', 'Service – Beschriftung', 'Export & Zulassung', 'Bildkacheln'),
    ('tile_finance', 'Finanzierung – Beschriftung', 'Finanzieren Sie bequem', 'Bildkacheln'),
    ('inventory_title', 'Externer Bestand – Überschrift', 'Unser Fahrzeugbestand', 'Angebote'),
    ('featured_title', 'Interne Angebote – Überschrift', 'Aktuelle Angebote', 'Angebote'),
    ('featured_button', 'Button zum Bestand', 'Alle Fahrzeuge', 'Angebote'),
    ('featured_empty', 'Text bei leerem Bestand', 'Derzeit sind keine veröffentlichten Fahrzeuge verfügbar.', 'Angebote'),
    ('finance_title', 'Überschrift', 'Finanzierung', 'Finanzierung'),
    ('finance_text', 'Einführung', 'Ein Auto ist eine Investition für viele Jahre – deshalb soll die Finanzierung zu Ihrer Situation passen. Bei Auto Wallstein unterstützen wir Sie dabei, eine passende Rate, Laufzeit und (auf Wunsch) eine Anzahlung zu wählen. Gemeinsam finden wir eine Lösung, die transparent, planbar und fair ist.', 'Finanzierung'),
    ('finance_more', 'Weiterer Text', 'Sprechen Sie uns gerne an – wir erstellen Ihnen ein individuelles Angebot und erklären Ihnen alle Schritte verständlich, damit Sie sicher entscheiden können.', 'Finanzierung'),
    ('finance_benefits', 'Vorteile', 'Ihre Vorteile: schnelle Rückmeldung, unkomplizierte Abwicklung, Finanzierung auch ohne Anzahlung möglich.', 'Finanzierung'),
    ('visit_title', 'Überschrift', 'Besuchen Sie uns in Heusenstamm', 'Besuch & Öffnungszeiten'),
    ('visit_text', 'Text für Ersatz-Slide', 'Wir freuen uns auf Ihren Besuch. Beratung, Öffnungszeiten und Verkauf zu folgenden Zeiten:', 'Besuch & Öffnungszeiten'),
    ('hours_title', 'Öffnungszeiten – Überschrift', 'Öffnungszeiten', 'Besuch & Öffnungszeiten'),
    ('weekdays', 'Montag bis Freitag', '09:00 – 13:00 / 14:30 – 18:00', 'Besuch & Öffnungszeiten'),
    ('saturday', 'Samstag', '10:00 – 14:00', 'Besuch & Öffnungszeiten'),
    ('sunday', 'Sonntag', 'Geschlossen', 'Besuch & Öffnungszeiten'),
    ('location_contact_title', 'Kontaktkasten – Überschrift', 'Anfahrt & Kontakt', 'Besuch & Öffnungszeiten'),
    ('appointment_title', 'Termin – Überschrift', 'Möchten Sie eine Probefahrt vereinbaren?', 'Besuch & Öffnungszeiten'),
    ('appointment_text', 'Termin – Text', 'Gerne nehmen wir uns Zeit für Sie. Vereinbaren Sie vorab einen Termin.', 'Besuch & Öffnungszeiten'),
    ('appointment_button', 'Termin – Button', 'Termin anfragen', 'Besuch & Öffnungszeiten'),
    ('contact_title', 'Überschrift', 'Kontaktieren Sie uns', 'Kontakt'),
    ('contact_text', 'Text für Ersatz-Slide', 'Wir beraten Sie gerne persönlich zu Ihrem neuen Mercedes-Benz.', 'Kontakt'),
    ('phone_label', 'Telefon – Beschriftung', 'Telefon', 'Kontakt'),
    ('phone_text', 'Telefon – Text', 'Rufen Sie uns direkt an', 'Kontakt'),
    ('email_label', 'E-Mail – Beschriftung', 'E-Mail', 'Kontakt'),
    ('email_text', 'E-Mail – Text', 'Schreiben Sie uns Ihr Anliegen', 'Kontakt'),
    ('business_name', 'Firmenname', 'Auto Wallstein', 'Kontaktdaten'),
    ('street', 'Straße und Hausnummer', 'Rudolf-Braas-Straße 27a', 'Kontaktdaten'),
    ('city', 'Postleitzahl und Ort', '63150 Heusenstamm', 'Kontaktdaten'),
    ('phone', 'Telefonnummer', '+49 6104 406770', 'Kontaktdaten'),
    ('email', 'E-Mail-Adresse', 'verkauf@auto-wallstein.de', 'Kontaktdaten'),
    ('accessories_title', 'Zubehör – Überschrift', 'Teile & Zubehör', 'Angebote'),
    ('accessories_text', 'Zubehör – Text', 'Entdecken Sie unsere Angebote für Reifen, Felgen und Autoteile.', 'Angebote'),
    ('accessories_button', 'Zubehör – Button', 'Teile & Zubehör ansehen', 'Angebote'),
    ('news_title', 'Neuigkeiten – Überschrift', 'Neuigkeiten', 'Angebote'),
    ('news_button', 'Neuigkeiten – Button', 'Alle Beiträge', 'Angebote'),
    ('vehicles_image_alt', 'Bildbeschreibung Fahrzeugsuche', 'Fahrzeugsuche', 'Bildkacheln'),
    ('service_image_alt', 'Bildbeschreibung Service', 'Export und Zulassung', 'Bildkacheln'),
    ('finance_image_alt', 'Bildbeschreibung Finanzierung', 'Finanzierung', 'Bildkacheln'),
    ('map_title', 'Anfahrt – Überschrift', 'Anfahrt', 'Anfahrt'),
    ('map_button', 'Navigation – Button', 'Route berechnen & Navigation starten', 'Anfahrt'),
]
IMAGE_FIELDS = [
    ('vehicles_image', 'Bild Fahrzeugsuche', 'images/Dino.jpeg', 'Bildkacheln'),
    ('service_image', 'Bild Service', 'images/krass.JPG', 'Bildkacheln'),
    ('finance_image', 'Bild Finanzierung', 'images/finanzierung.jpg', 'Bildkacheln'),
]
